### ISSUE TITLE
Release 0.3.0 ?

### ISSUE THREAD

**Issue by BDelacour** [messagebird/sachet#106]
Hey @marcelcorso 

May you release the project please ?

Thank you :)

**Comment by marcelcorso** [comment]
Yes! Very soon.

**Comment by marcelcorso** [comment]
The release is up 
https://github.com/messagebird/sachet/releases/tag/0.3.0

I'll push to docker hub later today when I have better internet (I'm in Belgium🇧🇪  on a train! 🚂 )

**Comment by BDelacour** [comment]
That's so cool !! Thank you so much !

**Comment by BDelacour** [comment]
Hey @marcelcorso, just a reminder if you have time to push to Docker Hub (and also generate the binary in the release) someday 👍
Thank you :)

**Comment by marcelcorso** [comment]
thanks @BDelacour. I got distracted in London 🇬🇧 and failed to do this earlier. 

It's up!

**Comment by BDelacour** [comment]
Thanks @marcelcorso !
I can see the new tag on Docker hub 🥳

Sorry for bothering you again but, can you add the binary in the release assets like you did in previous versions please ?

**Comment by marcelcorso** [comment]
@BDelacour done!

**Comment by BDelacour** [comment]
Thank you !
