### ISSUE TITLE
Feature request: Please add TextMagic as a provider

### ISSUE THREAD

**Issue by andrewdbate** [messagebird/sachet#109]
Please add [TextMagic](https://textmagic.com) as a provider.

TextMagic provide a Go API here: https://github.com/textmagic/textmagic-rest-go-v2

The README provides an example of how to send an SMS message using the Go API. A TextMagic trial account can be created at https://www.textmagic.com/ and comes with 10 free SMS messages for testing.

The API just requires a username and an API key, so that only those two things need to be specified in the yaml configuration.

(Please note that the v2 API should be used instead of the old v1 API which is still available [here](https://github.com/textmagic/textmagic-rest-go).)

It should be possible to use the MessageBird provider code (see [here](https://github.com/messagebird/sachet/blob/master/provider/messagebird/messagebird.go)) as a starting point and adapt it as required.

If I were to create a PR, would this be something you would consider merging? Many thanks!

**Comment by marcelcorso** [comment]
hey @andrewdbate! 
TextMagic looks good. We would definitely consider merging if you send us a PR! Please do!

**Comment by andrewdbate** [comment]
Closing this issue because the above PR has been merged.
