### ISSUE TITLE
When an sms is about more than one firing or resolved alert the text is not useful

### ISSUE THREAD

**Issue by marcelcorso** [messagebird/sachet#13]
Right now you get things like 

```
Firing: 3, Resolved: 0
Firing: 2, Resolved: 0
Firing: 2, Resolved: 0
Firing: 3, Resolved: 0
Firing: 0, Resolved: 2
```

and that doesn't tell much. 

It's hard to keep it short because you don't know what labels are important.

**Comment by marcelcorso** [comment]
I was thinking we could do like this:

```
Firing:
NginxStatusHighErrorRate instance=a.messagebird.com
NginxStatusHighErrorRate instance=b.messagebird.com
Resolved:
NginxStatusHighErrorRate instance=c.messagebird.com
NginxStatusHighErrorRate instance=d.messagebird.com
```

just the alertnames and the instances as a tentative solution

**Comment by EdSchouten** [comment]
We recently upgraded to the latest version of Sachet and also noticed this. I remember I previously sent a pull request to at least show all common labels, which worked very well in our case.

**Comment by marcelcorso** [comment]
Hey @EdSchouten I just found your commit that solved this here
https://github.com/messagebird/sachet/pull/4/files#r99210749

It didn't work for some cases for us at messagebird: when alerts share few labels it also gets hard to understand what is happening. 

I did a pull request a few days ago: 
https://github.com/messagebird/sachet/compare/better-multiple-alert-msgs

Any comments?

I think we have to put a cap on the amount of alerts to put on a sms. If 100 alerts are firing the message can get pretty big and end up not delivering.

**Comment by EdSchouten** [comment]
What about doing both? Keep the "Firing: ... Resolved: ..." in there, but print the common labels afterwards.

**Comment by EdSchouten** [comment]
Friendly ping. :-)

**Comment by marcelcorso** [comment]
Hi @EdSchouten. Thanks for the ping. 
This is also driving us 🔩  internally but we didn't had time to fix it yet. 

Again, just printing the common labels is not enough. Different sets of alerts may share nothing and then you would also get not enough information.

What @samwierema thinks about it? Or even @faizann that gets alerts every day :-) ?

**Comment by marcelcorso** [comment]
Hey @EdSchouten. We decided to go with the code on the [pull request number 4](https://github.com/messagebird/sachet/pull/4). Let's all try it out for a bit and see how it goes. 

Let us know if you learn something new.
