### ISSUE TITLE
Ability to add provider specific options

### ISSUE THREAD

**Issue by timstoop** [messagebird/sachet#17]
Currently, we use this in combination with MessageBird, but it defaults on the SMS Basic gateway. We'd like to use the Business+ gateway, as the text messages send are business critical (monitoring) and apparantly, the Basic gateway only sent 2 out of 15 messages last night, causing a disruption.

Although the go-rest-api from MessageBird allows setting of the gateway, this is not possible via Sachet. Unless I missed an option?

**Comment by samwierema** [comment]
Hi @timstoop, thanks for opening an issue. This sounds like a good idea! We'll be thinking of a solution to this issue. Of course, if you'd like to take a shot at it yourself, we'd be more than happy to see the contribution. 

P.S. sorry to hear about the messages not arriving. Could you contact support@messagebird.com about that? I've already notified them of this issue.

**Comment by marcelcorso** [comment]
Hey @timstoop. 
Because go is typed it's hard to come up with a "generic" way to pass params to providers without using empty interfaces and other hacks.  

The way @EdSchouten is the way to go I think. 
Also it solves your gateway example . So I think we are done 👍 !
