### ISSUE TITLE
Support for voice messaging?

### ISSUE THREAD

**Issue by siavashs** [messagebird/sachet#29]
We need to send some alerts using [voice messaging](https://developers.messagebird.com/docs/voice)
I'm willing to implement this, but wanted to read your comments first.

**Comment by samwierema** [comment]
@siavashs thanks for opening an issue. We definitely would like to see an implementation of the voice messaging endpoint. Not 100% sure how it would integrate into the existing MessageBird provider, but looking forward to see your implementation. 

Please ping us if you have specific questions, or need guidance/feedback.

**Comment by siavashs** [comment]
Sorry for the very late reply. This happened while I was switching jobs.
I just reminded about this while signing up for the Go Meetup in Amsterdam 😄 
Anyway here is the implementation I did back then: https://github.com/catawiki/sachet/commit/7766fbf6a3217b2c05b9b1c051426ec609b577fd
Let me know if you are interested.

**Comment by marcelcorso** [comment]
@siavashs ha! @idsvandermolen did something https://github.com/messagebird/sachet/pull/66 :-D

**Comment by siavashs** [comment]
Cool, I'll close this then!
