### ISSUE TITLE
Url for reloading the configuration

### ISSUE THREAD

**Issue by andreaskundig** [messagebird/sachet#38]
I need to add/remove receivers dynamically. I'd like to generate a new config file and tell sachet to reload it.

It would be nice to have the same url as Prometheus and the alert manager which reload their configuration when they receive an HTTP POST request to the /-/reload endpoint.

https://prometheus.io/docs/prometheus/latest/configuration/configuration/
https://prometheus.io/docs/alerting/configuration/

**Comment by marcelcorso** [comment]
I like this! It's not hard to implement and its a common use case. I can't guarantee messagebird will implement this timely because we don't have that problem (we deploy the whole thing when the config changes). 

we would love a pull request!

**Comment by andreaskundig** [comment]
Here you are: https://github.com/messagebird/sachet/pull/39
