### ISSUE TITLE
integrate sachet with nowsms

### ISSUE THREAD

**Issue by mootezbessifi** [messagebird/sachet#67]
Hi folks,

we have our sms gateway called nowsms, how to integrate it with prometheus using sachet.? 
your answers are highly appreciated 

thanks

**Comment by marcelcorso** [comment]
hey @mootezbessifi! 
You need to create a new provider struct that implements the Provider interface https://github.com/messagebird/sachet/blob/ac5f01cd9cf1fb74974541f75f6179a28726d6e6/sachet.go#L3 

that struct should go in "nowsms" a package inside the provider package https://github.com/messagebird/sachet/tree/master/provider. 

The provider code is not super hard. Take MessageBird for example:
https://github.com/messagebird/sachet/blob/master/provider/messagebird/messagebird.go

It has the provider struct (MessageBird) that implements the `Send` method: that's where the secret sauce of nowsms should go... for example you would do an http request there. 

Apart from that you would need a configuration structure https://github.com/messagebird/sachet/blob/master/provider/messagebird/messagebird.go#L11 to pass secrets (api keys etc) to the provider. 

Plus some other small things. For that take a look at the PR that added the last provider as an example: 
https://github.com/messagebird/sachet/pull/61

I would like to ask you to someone from your team to do that PR. 🙏

**Comment by mootezbessifi** [comment]
Hi @marcelcorso,
thank you for your quick answer.
PS: to call nowsms, its an http post call like following:
http://smsnow-ip-port/send?User=*****&Password=*****&PhoneNumber=*********&Text=******

what is the best existing provider template which i can use to implement this?

another question please, how may i pass the alertmanager sms body template to sachet. because i want a dynamic sms body to fit with the kind of alert (alert name, params, etc).

**Comment by mootezbessifi** [comment]
Hi @marcelcorso,
please may you review the [PR](https://github.com/messagebird/sachet/pull/69) regarding nowsms provider implementation. it is done by one of our developers.

PS: i tested it in our env and it is working fine.

thank you
