### ISSUE TITLE
Assistance: provider development

### ISSUE THREAD

**Issue by VoidAndAny** [messagebird/sachet#75]
Hi, 
First of all, I'm a complete beginner in Go but I try to develop a provider for OVH.

I successfully created a standalone program sending SMS throught OVH API, but I can't make it work with Sachet.

First of all, how do you test and debug sachet ?
I must run '''go run  main.go config.go telemetry.go''' from cmd/sachet directory, then test with curl request, if it doesn't work properly, CTRL+C Sachet, make the correction and restart ?

I made an ovh.go file containing my code but I can't make it "visible" by sachet.
I look into this [commit](https://github.com/messagebird/sachet/commit/3cf03554ae085533a7eb8cf82e9c02016c0fe67a#diff-37aff102a57d3d7b797f152915a6dc16) to see what files must be changed.
I modified, main.go and config.go, but not go.mod neither go.sum, must I ? 
I am at early stage of development so my module/package is not hosted on github, so how can I include/import it ?

I tried, unsuccessfully, to make dot import related to this error : 
```
build command-line-arguments: cannot load provider/ovh: malformed module path "ovh": missing dot in first path element
```

Maybe, this issue is not the right place to have information, feel free to close it.

Thanks
Yoann

**Comment by marcelcorso** [comment]
hey @VoidAndAny it's easier to help if we can see the code. Please for the repo and push your changes. 
Also if you are beginner of go I recommend you to read:
https://golang.org/doc/code.html

and more specifically on go.mod and go.sum:
https://blog.golang.org/using-go-modules

**Comment by VoidAndAny** [comment]
Hi, 
thank, finally found how to do (with help of my collegue), PR is coming.
Hope I do it correctly
Yoann
