### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by VoidAndAny** [messagebird/sachet#78]
Hi, 
Thanks for the merge, will you create a new release soon ?
My Ansible role used to deploy sachet is based on github release, I will find another way to deploy my version of Sachet (with OVH provider) but it would be nice if you make a new release.

Thanks a lot
Yoann

**Comment by marcelcorso** [comment]
https://github.com/messagebird/sachet/releases/tag/0.2.3 👍

**Comment by VoidAndAny** [comment]
Merci / Thank you :D
