### ISSUE TITLE
github.com/tencentcloud/tencentcloud-sdk-go/go.mod at revision v3.0.164: unknown revision v3.0.164

### ISSUE THREAD

**Issue by ddevault** [messagebird/sachet#93]
This version doesn't seem to exist anymore. You may have to set `GOPROXY=direct` to reproduce this.

**Comment by ddevault** [comment]
This is still reproducible.

**Comment by ddevault** [comment]
New release. Still reproducible.

**Comment by marcelcorso** [comment]
hey @ddevault I tried `OPROXY=direct` but I failed to reproduce. Can you share the steps you do to get there?

**Comment by ddevault** [comment]
This seems to happen when running `go mod vendor`, which is a standard practice for some downstream distributions.

**Comment by ddevault** [comment]
`go mod tidy` also produces this error.

**Comment by ddevault** [comment]
Can confirm the fix. Thanks!

**Comment by marcelcorso** [comment]
Finally! Thanks for the report. 🎉
